#define GBUFFER_DEBUG_NONE 0
#define GBUFFER_DEBUG_ALBEDO 1
#define GBUFFER_DEBUG_EMISSION 2
#define GBUFFER_DEBUG_NORMAL 3
#define GBUFFER_DEBUG_MATERIAL_PROPERTIES 4
#define GBUFFER_DEBUG_WORLD_POSITION 5
#define GBUFFER_DEBUG_NAIVE_POINT_LIGHT_NO_SHADOW 6
